import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';

const MethodChannel _androidDtmfChannel = MethodChannel('ocn/dtmf');

/// DTMF (touch-tone) frequencies per key: low/high row-column pairs.
const Map<String, (int, int)> dtmfFrequencies = {
  '1': (697, 1209),
  '2': (697, 1336),
  '3': (697, 1477),
  '4': (770, 1209),
  '5': (770, 1336),
  '6': (770, 1477),
  '7': (852, 1209),
  '8': (852, 1336),
  '9': (852, 1477),
  '*': (941, 1209),
  '0': (941, 1336),
  '#': (941, 1477),
};

bool isDtmfKey(String key) => dtmfFrequencies.containsKey(key);

/// Synthesizes a short dual-tone DTMF burst as a complete WAV file
/// (PCM 16-bit mono). Pure function so it can be unit tested.
Uint8List buildDtmfWav(String key, {int ms = 90, int sampleRate = 22050}) {
  final freqs = dtmfFrequencies[key];
  if (freqs == null) {
    throw ArgumentError('"$key" is not a DTMF key');
  }
  final (low, high) = freqs;
  final sampleCount = sampleRate * ms ~/ 1000;
  final fadeSamples = (sampleRate * 5 ~/ 1000); // 5ms fades to avoid clicks

  final pcm = ByteData(sampleCount * 2);
  for (var i = 0; i < sampleCount; i++) {
    final t = i / sampleRate;
    var env = 1.0;
    if (i < fadeSamples) env = i / fadeSamples;
    if (i > sampleCount - fadeSamples) env = (sampleCount - i) / fadeSamples;
    final v = 0.5 * (math.sin(2 * math.pi * low * t) + math.sin(2 * math.pi * high * t)) * env;
    pcm.setInt16(i * 2, (v * 16000).round(), Endian.little);
  }

  final bytes = ByteData(44 + sampleCount * 2);
  void writeString(int offset, String s) {
    for (var i = 0; i < s.length; i++) {
      bytes.setUint8(offset + i, s.codeUnitAt(i));
    }
  }

  writeString(0, 'RIFF');
  bytes.setUint32(4, 36 + sampleCount * 2, Endian.little);
  writeString(8, 'WAVE');
  writeString(12, 'fmt ');
  bytes.setUint32(16, 16, Endian.little);
  bytes.setUint16(20, 1, Endian.little); // PCM
  bytes.setUint16(22, 1, Endian.little); // mono
  bytes.setUint32(24, sampleRate, Endian.little);
  bytes.setUint32(28, sampleRate * 2, Endian.little); // byte rate
  bytes.setUint16(32, 2, Endian.little); // block align
  bytes.setUint16(34, 16, Endian.little); // bits per sample
  writeString(36, 'data');
  bytes.setUint32(40, sampleCount * 2, Endian.little);
  for (var i = 0; i < sampleCount * 2; i++) {
    bytes.setUint8(44 + i, pcm.getUint8(i));
  }

  return bytes.buffer.asUint8List();
}

/// Plays local DTMF feedback tones for keypad presses.
///
/// On Android the tone is generated by the system ToneGenerator and routed to
/// the earpiece (like a real phone keypad). Elsewhere (desktop) we synthesize
/// a WAV and play it with audioplayers.
class DtmfTones {
  DtmfTones._();

  static AudioPlayer? _player;
  static final Map<String, Uint8List> _cache = {};

  static Future<void> play(String key) async {
    if (!isDtmfKey(key)) return;
    try {
      if (Platform.isAndroid) {
        await _androidDtmfChannel.invokeMethod<void>('tone', {'key': key});
        return;
      }
      final player = _player ??= AudioPlayer();
      await player.setPlayerMode(PlayerMode.lowLatency);
      final wav = _cache.putIfAbsent(key, () => buildDtmfWav(key));
      await player.stop();
      await player.play(BytesSource(wav));
    } catch (_) {
      // Tones are cosmetic feedback; never let them break the dialer.
    }
  }
}
