// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: registry.proto

package registry

import (
	common "github.com/open-carrier-network/ocn/registry/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Push a data message to a single device via the shared Firebase project.
type PushDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallerNumber  string                 `protobuf:"bytes,3,opt,name=caller_number,json=callerNumber,proto3" json:"caller_number,omitempty"` // 7-digit or full? formatted number string
	CallerName    string                 `protobuf:"bytes,4,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"`
	AreaCode      string                 `protobuf:"bytes,5,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"` // sending server's area code (for auth/audit)
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // unix seconds; signed by the calling server
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`               // Ed25519 over area_code|timestamp|token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDeviceRequest) Reset() {
	*x = PushDeviceRequest{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDeviceRequest) ProtoMessage() {}

func (x *PushDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDeviceRequest.ProtoReflect.Descriptor instead.
func (*PushDeviceRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *PushDeviceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushDeviceRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *PushDeviceRequest) GetCallerNumber() string {
	if x != nil {
		return x.CallerNumber
	}
	return ""
}

func (x *PushDeviceRequest) GetCallerName() string {
	if x != nil {
		return x.CallerName
	}
	return ""
}

func (x *PushDeviceRequest) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *PushDeviceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PushDeviceRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// OCNServer registration
type RegisterOCNServerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ServerAddress      string                 `protobuf:"bytes,3,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`                  // gRPC endpoint for this ocnserver
	OcnserverPublicKey []byte                 `protobuf:"bytes,4,opt,name=ocnserver_public_key,json=ocnserverPublicKey,proto3" json:"ocnserver_public_key,omitempty"` // Ed25519 public key for ocnserver identity
	RequestedAreaCode  string                 `protobuf:"bytes,5,opt,name=requested_area_code,json=requestedAreaCode,proto3" json:"requested_area_code,omitempty"`    // Optional preference, empty = auto-assign
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterOCNServerRequest) Reset() {
	*x = RegisterOCNServerRequest{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOCNServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOCNServerRequest) ProtoMessage() {}

func (x *RegisterOCNServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOCNServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterOCNServerRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOCNServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterOCNServerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterOCNServerRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *RegisterOCNServerRequest) GetOcnserverPublicKey() []byte {
	if x != nil {
		return x.OcnserverPublicKey
	}
	return nil
}

func (x *RegisterOCNServerRequest) GetRequestedAreaCode() string {
	if x != nil {
		return x.RequestedAreaCode
	}
	return ""
}

type RegisterOCNServerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedAreaCode string                 `protobuf:"bytes,2,opt,name=assigned_area_code,json=assignedAreaCode,proto3" json:"assigned_area_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterOCNServerResponse) Reset() {
	*x = RegisterOCNServerResponse{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOCNServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOCNServerResponse) ProtoMessage() {}

func (x *RegisterOCNServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOCNServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterOCNServerResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterOCNServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterOCNServerResponse) GetAssignedAreaCode() string {
	if x != nil {
		return x.AssignedAreaCode
	}
	return ""
}

func (x *RegisterOCNServerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeregisterOCNServerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AreaCode           string                 `protobuf:"bytes,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	OcnserverPublicKey []byte                 `protobuf:"bytes,2,opt,name=ocnserver_public_key,json=ocnserverPublicKey,proto3" json:"ocnserver_public_key,omitempty"` // Must sign to prove ownership
	Timestamp          int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                              // unix seconds
	Signature          []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                                               // Ed25519 over area_code|timestamp
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeregisterOCNServerRequest) Reset() {
	*x = DeregisterOCNServerRequest{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterOCNServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterOCNServerRequest) ProtoMessage() {}

func (x *DeregisterOCNServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterOCNServerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterOCNServerRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterOCNServerRequest) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *DeregisterOCNServerRequest) GetOcnserverPublicKey() []byte {
	if x != nil {
		return x.OcnserverPublicKey
	}
	return nil
}

func (x *DeregisterOCNServerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeregisterOCNServerRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// OCNServer directory
type OCNServerInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AreaCode           string                 `protobuf:"bytes,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ServerAddress      string                 `protobuf:"bytes,4,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	OcnserverPublicKey []byte                 `protobuf:"bytes,5,opt,name=ocnserver_public_key,json=ocnserverPublicKey,proto3" json:"ocnserver_public_key,omitempty"`
	RegisteredAt       int64                  `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "ACTIVE", "SUSPENDED"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OCNServerInfo) Reset() {
	*x = OCNServerInfo{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCNServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCNServerInfo) ProtoMessage() {}

func (x *OCNServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCNServerInfo.ProtoReflect.Descriptor instead.
func (*OCNServerInfo) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *OCNServerInfo) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *OCNServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OCNServerInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OCNServerInfo) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *OCNServerInfo) GetOcnserverPublicKey() []byte {
	if x != nil {
		return x.OcnserverPublicKey
	}
	return nil
}

func (x *OCNServerInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *OCNServerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListOCNServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOCNServersRequest) Reset() {
	*x = ListOCNServersRequest{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOCNServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOCNServersRequest) ProtoMessage() {}

func (x *ListOCNServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOCNServersRequest.ProtoReflect.Descriptor instead.
func (*ListOCNServersRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ListOCNServersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOCNServersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOCNServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ocnservers    []*OCNServerInfo       `protobuf:"bytes,1,rep,name=ocnservers,proto3" json:"ocnservers,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOCNServersResponse) Reset() {
	*x = ListOCNServersResponse{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOCNServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOCNServersResponse) ProtoMessage() {}

func (x *ListOCNServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOCNServersResponse.ProtoReflect.Descriptor instead.
func (*ListOCNServersResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ListOCNServersResponse) GetOcnservers() []*OCNServerInfo {
	if x != nil {
		return x.Ocnservers
	}
	return nil
}

func (x *ListOCNServersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Routing
type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaCode      string                 `protobuf:"bytes,1,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteRequest) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Ocnserver     *OCNServerInfo         `protobuf:"bytes,2,opt,name=ocnserver,proto3" json:"ocnserver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetRouteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetRouteResponse) GetOcnserver() *OCNServerInfo {
	if x != nil {
		return x.Ocnserver
	}
	return nil
}

// Resolve a full 800/900 service number to its hosting exchange.
type ResolveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullNumber    string                 `protobuf:"bytes,1,opt,name=full_number,json=fullNumber,proto3" json:"full_number,omitempty"` // 10 digits, e.g. "8007766001"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceRequest) Reset() {
	*x = ResolveServiceRequest{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceRequest) ProtoMessage() {}

func (x *ResolveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceRequest.ProtoReflect.Descriptor instead.
func (*ResolveServiceRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveServiceRequest) GetFullNumber() string {
	if x != nil {
		return x.FullNumber
	}
	return ""
}

type ResolveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Ocnserver     *OCNServerInfo         `protobuf:"bytes,2,opt,name=ocnserver,proto3" json:"ocnserver,omitempty"` // hosting exchange
	FullNumber    string                 `protobuf:"bytes,3,opt,name=full_number,json=fullNumber,proto3" json:"full_number,omitempty"`
	Vanity        string                 `protobuf:"bytes,4,opt,name=vanity,proto3" json:"vanity,omitempty"` // e.g. "ROO-M001"
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceResponse) Reset() {
	*x = ResolveServiceResponse{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceResponse) ProtoMessage() {}

func (x *ResolveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceResponse.ProtoReflect.Descriptor instead.
func (*ResolveServiceResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveServiceResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveServiceResponse) GetOcnserver() *OCNServerInfo {
	if x != nil {
		return x.Ocnserver
	}
	return nil
}

func (x *ResolveServiceResponse) GetFullNumber() string {
	if x != nil {
		return x.FullNumber
	}
	return ""
}

func (x *ResolveServiceResponse) GetVanity() string {
	if x != nil {
		return x.Vanity
	}
	return ""
}

func (x *ResolveServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveServiceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// STUN
type ICECandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // kSIM public key or session ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidateRequest) Reset() {
	*x = ICECandidateRequest{}
	mi := &file_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidateRequest) ProtoMessage() {}

func (x *ICECandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidateRequest.ProtoReflect.Descriptor instead.
func (*ICECandidateRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{11}
}

func (x *ICECandidateRequest) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

type ICECandidateResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Candidates             []*common.ICECandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	ServerReflexiveAddress string                 `protobuf:"bytes,2,opt,name=server_reflexive_address,json=serverReflexiveAddress,proto3" json:"server_reflexive_address,omitempty"` // STUN-derived public IP:port
	IceServers             []*ICEServer           `protobuf:"bytes,3,rep,name=ice_servers,json=iceServers,proto3" json:"ice_servers,omitempty"`                                       // STUN/TURN servers clients should use
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ICECandidateResponse) Reset() {
	*x = ICECandidateResponse{}
	mi := &file_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidateResponse) ProtoMessage() {}

func (x *ICECandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidateResponse.ProtoReflect.Descriptor instead.
func (*ICECandidateResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{12}
}

func (x *ICECandidateResponse) GetCandidates() []*common.ICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ICECandidateResponse) GetServerReflexiveAddress() string {
	if x != nil {
		return x.ServerReflexiveAddress
	}
	return ""
}

func (x *ICECandidateResponse) GetIceServers() []*ICEServer {
	if x != nil {
		return x.IceServers
	}
	return nil
}

// An ICE server entry (mirrors WebRTC RTCIceServer).
type ICEServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`             // e.g. "stun:stun.l.google.com:19302", "turn:host:3478?transport=udp"
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`     // TURN long-term credential user ("" for STUN)
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"` // TURN password ("" for STUN)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICEServer) Reset() {
	*x = ICEServer{}
	mi := &file_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICEServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICEServer) ProtoMessage() {}

func (x *ICEServer) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICEServer.ProtoReflect.Descriptor instead.
func (*ICEServer) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ICEServer) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ICEServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ICEServer) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\focn.registry\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe1\x01\n" +
	"\x11PushDeviceRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12#\n" +
	"\rcaller_number\x18\x03 \x01(\tR\fcallerNumber\x12\x1f\n" +
	"\vcaller_name\x18\x04 \x01(\tR\n" +
	"callerName\x12\x1b\n" +
	"\tarea_code\x18\x05 \x01(\tR\bareaCode\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xd9\x01\n" +
	"\x18RegisterOCNServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0eserver_address\x18\x03 \x01(\tR\rserverAddress\x120\n" +
	"\x14ocnserver_public_key\x18\x04 \x01(\fR\x12ocnserverPublicKey\x12.\n" +
	"\x13requested_area_code\x18\x05 \x01(\tR\x11requestedAreaCode\"\x88\x01\n" +
	"\x19RegisterOCNServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x12assigned_area_code\x18\x02 \x01(\tR\x10assignedAreaCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa7\x01\n" +
	"\x1aDeregisterOCNServerRequest\x12\x1b\n" +
	"\tarea_code\x18\x01 \x01(\tR\bareaCode\x120\n" +
	"\x14ocnserver_public_key\x18\x02 \x01(\fR\x12ocnserverPublicKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xf8\x01\n" +
	"\rOCNServerInfo\x12\x1b\n" +
	"\tarea_code\x18\x01 \x01(\tR\bareaCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0eserver_address\x18\x04 \x01(\tR\rserverAddress\x120\n" +
	"\x14ocnserver_public_key\x18\x05 \x01(\fR\x12ocnserverPublicKey\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x03R\fregisteredAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"H\n" +
	"\x15ListOCNServersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"v\n" +
	"\x16ListOCNServersResponse\x12;\n" +
	"\n" +
	"ocnservers\x18\x01 \x03(\v2\x1b.ocn.registry.OCNServerInfoR\n" +
	"ocnservers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\".\n" +
	"\x0fGetRouteRequest\x12\x1b\n" +
	"\tarea_code\x18\x01 \x01(\tR\bareaCode\"c\n" +
	"\x10GetRouteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x129\n" +
	"\tocnserver\x18\x02 \x01(\v2\x1b.ocn.registry.OCNServerInfoR\tocnserver\"8\n" +
	"\x15ResolveServiceRequest\x12\x1f\n" +
	"\vfull_number\x18\x01 \x01(\tR\n" +
	"fullNumber\"\xd8\x01\n" +
	"\x16ResolveServiceResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x129\n" +
	"\tocnserver\x18\x02 \x01(\v2\x1b.ocn.registry.OCNServerInfoR\tocnserver\x12\x1f\n" +
	"\vfull_number\x18\x03 \x01(\tR\n" +
	"fullNumber\x12\x16\n" +
	"\x06vanity\x18\x04 \x01(\tR\x06vanity\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"2\n" +
	"\x13ICECandidateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\"\xc4\x01\n" +
	"\x14ICECandidateResponse\x128\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x18.ocn.common.ICECandidateR\n" +
	"candidates\x128\n" +
	"\x18server_reflexive_address\x18\x02 \x01(\tR\x16serverReflexiveAddress\x128\n" +
	"\vice_servers\x18\x03 \x03(\v2\x17.ocn.registry.ICEServerR\n" +
	"iceServers\"[\n" +
	"\tICEServer\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential2\xf3\x04\n" +
	"\vOCNRegistry\x12d\n" +
	"\x11RegisterOCNServer\x12&.ocn.registry.RegisterOCNServerRequest\x1a'.ocn.registry.RegisterOCNServerResponse\x12W\n" +
	"\x13DeregisterOCNServer\x12(.ocn.registry.DeregisterOCNServerRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x0eListOCNServers\x12#.ocn.registry.ListOCNServersRequest\x1a$.ocn.registry.ListOCNServersResponse\x12I\n" +
	"\bGetRoute\x12\x1d.ocn.registry.GetRouteRequest\x1a\x1e.ocn.registry.GetRouteResponse\x12[\n" +
	"\x0eResolveService\x12#.ocn.registry.ResolveServiceRequest\x1a$.ocn.registry.ResolveServiceResponse\x12Y\n" +
	"\x10GetICECandidates\x12!.ocn.registry.ICECandidateRequest\x1a\".ocn.registry.ICECandidateResponse\x12E\n" +
	"\n" +
	"PushDevice\x12\x1f.ocn.registry.PushDeviceRequest\x1a\x16.google.protobuf.EmptyB4Z2github.com/open-carrier-network/ocn/proto/registryb\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_registry_proto_goTypes = []any{
	(*PushDeviceRequest)(nil),          // 0: ocn.registry.PushDeviceRequest
	(*RegisterOCNServerRequest)(nil),   // 1: ocn.registry.RegisterOCNServerRequest
	(*RegisterOCNServerResponse)(nil),  // 2: ocn.registry.RegisterOCNServerResponse
	(*DeregisterOCNServerRequest)(nil), // 3: ocn.registry.DeregisterOCNServerRequest
	(*OCNServerInfo)(nil),              // 4: ocn.registry.OCNServerInfo
	(*ListOCNServersRequest)(nil),      // 5: ocn.registry.ListOCNServersRequest
	(*ListOCNServersResponse)(nil),     // 6: ocn.registry.ListOCNServersResponse
	(*GetRouteRequest)(nil),            // 7: ocn.registry.GetRouteRequest
	(*GetRouteResponse)(nil),           // 8: ocn.registry.GetRouteResponse
	(*ResolveServiceRequest)(nil),      // 9: ocn.registry.ResolveServiceRequest
	(*ResolveServiceResponse)(nil),     // 10: ocn.registry.ResolveServiceResponse
	(*ICECandidateRequest)(nil),        // 11: ocn.registry.ICECandidateRequest
	(*ICECandidateResponse)(nil),       // 12: ocn.registry.ICECandidateResponse
	(*ICEServer)(nil),                  // 13: ocn.registry.ICEServer
	(*common.ICECandidate)(nil),        // 14: ocn.common.ICECandidate
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
}
var file_registry_proto_depIdxs = []int32{
	4,  // 0: ocn.registry.ListOCNServersResponse.ocnservers:type_name -> ocn.registry.OCNServerInfo
	4,  // 1: ocn.registry.GetRouteResponse.ocnserver:type_name -> ocn.registry.OCNServerInfo
	4,  // 2: ocn.registry.ResolveServiceResponse.ocnserver:type_name -> ocn.registry.OCNServerInfo
	14, // 3: ocn.registry.ICECandidateResponse.candidates:type_name -> ocn.common.ICECandidate
	13, // 4: ocn.registry.ICECandidateResponse.ice_servers:type_name -> ocn.registry.ICEServer
	1,  // 5: ocn.registry.OCNRegistry.RegisterOCNServer:input_type -> ocn.registry.RegisterOCNServerRequest
	3,  // 6: ocn.registry.OCNRegistry.DeregisterOCNServer:input_type -> ocn.registry.DeregisterOCNServerRequest
	5,  // 7: ocn.registry.OCNRegistry.ListOCNServers:input_type -> ocn.registry.ListOCNServersRequest
	7,  // 8: ocn.registry.OCNRegistry.GetRoute:input_type -> ocn.registry.GetRouteRequest
	9,  // 9: ocn.registry.OCNRegistry.ResolveService:input_type -> ocn.registry.ResolveServiceRequest
	11, // 10: ocn.registry.OCNRegistry.GetICECandidates:input_type -> ocn.registry.ICECandidateRequest
	0,  // 11: ocn.registry.OCNRegistry.PushDevice:input_type -> ocn.registry.PushDeviceRequest
	2,  // 12: ocn.registry.OCNRegistry.RegisterOCNServer:output_type -> ocn.registry.RegisterOCNServerResponse
	15, // 13: ocn.registry.OCNRegistry.DeregisterOCNServer:output_type -> google.protobuf.Empty
	6,  // 14: ocn.registry.OCNRegistry.ListOCNServers:output_type -> ocn.registry.ListOCNServersResponse
	8,  // 15: ocn.registry.OCNRegistry.GetRoute:output_type -> ocn.registry.GetRouteResponse
	10, // 16: ocn.registry.OCNRegistry.ResolveService:output_type -> ocn.registry.ResolveServiceResponse
	12, // 17: ocn.registry.OCNRegistry.GetICECandidates:output_type -> ocn.registry.ICECandidateResponse
	15, // 18: ocn.registry.OCNRegistry.PushDevice:output_type -> google.protobuf.Empty
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
