// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: registry.proto

package registry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCNRegistry_RegisterOCNServer_FullMethodName   = "/ocn.registry.OCNRegistry/RegisterOCNServer"
	OCNRegistry_DeregisterOCNServer_FullMethodName = "/ocn.registry.OCNRegistry/DeregisterOCNServer"
	OCNRegistry_ListOCNServers_FullMethodName      = "/ocn.registry.OCNRegistry/ListOCNServers"
	OCNRegistry_GetRoute_FullMethodName            = "/ocn.registry.OCNRegistry/GetRoute"
	OCNRegistry_ResolveService_FullMethodName      = "/ocn.registry.OCNRegistry/ResolveService"
	OCNRegistry_GetICECandidates_FullMethodName    = "/ocn.registry.OCNRegistry/GetICECandidates"
	OCNRegistry_PushDevice_FullMethodName          = "/ocn.registry.OCNRegistry/PushDevice"
)

// OCNRegistryClient is the client API for OCNRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OCNRegistryClient interface {
	// OCNServer management
	RegisterOCNServer(ctx context.Context, in *RegisterOCNServerRequest, opts ...grpc.CallOption) (*RegisterOCNServerResponse, error)
	DeregisterOCNServer(ctx context.Context, in *DeregisterOCNServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListOCNServers(ctx context.Context, in *ListOCNServersRequest, opts ...grpc.CallOption) (*ListOCNServersResponse, error)
	// Routing
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	ResolveService(ctx context.Context, in *ResolveServiceRequest, opts ...grpc.CallOption) (*ResolveServiceResponse, error)
	// STUN
	GetICECandidates(ctx context.Context, in *ICECandidateRequest, opts ...grpc.CallOption) (*ICECandidateResponse, error)
	// Push: lets a registered OCN server wake one of its offline devices using
	// the network's shared Firebase credential. Stateless (token passed per call).
	PushDevice(ctx context.Context, in *PushDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type oCNRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewOCNRegistryClient(cc grpc.ClientConnInterface) OCNRegistryClient {
	return &oCNRegistryClient{cc}
}

func (c *oCNRegistryClient) RegisterOCNServer(ctx context.Context, in *RegisterOCNServerRequest, opts ...grpc.CallOption) (*RegisterOCNServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterOCNServerResponse)
	err := c.cc.Invoke(ctx, OCNRegistry_RegisterOCNServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) DeregisterOCNServer(ctx context.Context, in *DeregisterOCNServerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OCNRegistry_DeregisterOCNServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) ListOCNServers(ctx context.Context, in *ListOCNServersRequest, opts ...grpc.CallOption) (*ListOCNServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOCNServersResponse)
	err := c.cc.Invoke(ctx, OCNRegistry_ListOCNServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, OCNRegistry_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) ResolveService(ctx context.Context, in *ResolveServiceRequest, opts ...grpc.CallOption) (*ResolveServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveServiceResponse)
	err := c.cc.Invoke(ctx, OCNRegistry_ResolveService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) GetICECandidates(ctx context.Context, in *ICECandidateRequest, opts ...grpc.CallOption) (*ICECandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ICECandidateResponse)
	err := c.cc.Invoke(ctx, OCNRegistry_GetICECandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNRegistryClient) PushDevice(ctx context.Context, in *PushDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OCNRegistry_PushDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCNRegistryServer is the server API for OCNRegistry service.
// All implementations must embed UnimplementedOCNRegistryServer
// for forward compatibility.
type OCNRegistryServer interface {
	// OCNServer management
	RegisterOCNServer(context.Context, *RegisterOCNServerRequest) (*RegisterOCNServerResponse, error)
	DeregisterOCNServer(context.Context, *DeregisterOCNServerRequest) (*emptypb.Empty, error)
	ListOCNServers(context.Context, *ListOCNServersRequest) (*ListOCNServersResponse, error)
	// Routing
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	ResolveService(context.Context, *ResolveServiceRequest) (*ResolveServiceResponse, error)
	// STUN
	GetICECandidates(context.Context, *ICECandidateRequest) (*ICECandidateResponse, error)
	// Push: lets a registered OCN server wake one of its offline devices using
	// the network's shared Firebase credential. Stateless (token passed per call).
	PushDevice(context.Context, *PushDeviceRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOCNRegistryServer()
}

// UnimplementedOCNRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCNRegistryServer struct{}

func (UnimplementedOCNRegistryServer) RegisterOCNServer(context.Context, *RegisterOCNServerRequest) (*RegisterOCNServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterOCNServer not implemented")
}
func (UnimplementedOCNRegistryServer) DeregisterOCNServer(context.Context, *DeregisterOCNServerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterOCNServer not implemented")
}
func (UnimplementedOCNRegistryServer) ListOCNServers(context.Context, *ListOCNServersRequest) (*ListOCNServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOCNServers not implemented")
}
func (UnimplementedOCNRegistryServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedOCNRegistryServer) ResolveService(context.Context, *ResolveServiceRequest) (*ResolveServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveService not implemented")
}
func (UnimplementedOCNRegistryServer) GetICECandidates(context.Context, *ICECandidateRequest) (*ICECandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetICECandidates not implemented")
}
func (UnimplementedOCNRegistryServer) PushDevice(context.Context, *PushDeviceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PushDevice not implemented")
}
func (UnimplementedOCNRegistryServer) mustEmbedUnimplementedOCNRegistryServer() {}
func (UnimplementedOCNRegistryServer) testEmbeddedByValue()                     {}

// UnsafeOCNRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCNRegistryServer will
// result in compilation errors.
type UnsafeOCNRegistryServer interface {
	mustEmbedUnimplementedOCNRegistryServer()
}

func RegisterOCNRegistryServer(s grpc.ServiceRegistrar, srv OCNRegistryServer) {
	// If the following call panics, it indicates UnimplementedOCNRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCNRegistry_ServiceDesc, srv)
}

func _OCNRegistry_RegisterOCNServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterOCNServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).RegisterOCNServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_RegisterOCNServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).RegisterOCNServer(ctx, req.(*RegisterOCNServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_DeregisterOCNServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterOCNServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).DeregisterOCNServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_DeregisterOCNServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).DeregisterOCNServer(ctx, req.(*DeregisterOCNServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_ListOCNServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOCNServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).ListOCNServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_ListOCNServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).ListOCNServers(ctx, req.(*ListOCNServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_ResolveService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).ResolveService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_ResolveService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).ResolveService(ctx, req.(*ResolveServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_GetICECandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ICECandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).GetICECandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_GetICECandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).GetICECandidates(ctx, req.(*ICECandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNRegistry_PushDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNRegistryServer).PushDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNRegistry_PushDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNRegistryServer).PushDevice(ctx, req.(*PushDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OCNRegistry_ServiceDesc is the grpc.ServiceDesc for OCNRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCNRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocn.registry.OCNRegistry",
	HandlerType: (*OCNRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOCNServer",
			Handler:    _OCNRegistry_RegisterOCNServer_Handler,
		},
		{
			MethodName: "DeregisterOCNServer",
			Handler:    _OCNRegistry_DeregisterOCNServer_Handler,
		},
		{
			MethodName: "ListOCNServers",
			Handler:    _OCNRegistry_ListOCNServers_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _OCNRegistry_GetRoute_Handler,
		},
		{
			MethodName: "ResolveService",
			Handler:    _OCNRegistry_ResolveService_Handler,
		},
		{
			MethodName: "GetICECandidates",
			Handler:    _OCNRegistry_GetICECandidates_Handler,
		},
		{
			MethodName: "PushDevice",
			Handler:    _OCNRegistry_PushDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
