// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ocnserver.proto

package ocnserver

import (
	common "github.com/open-carrier-network/ocn/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallEvent_Type int32

const (
	CallEvent_UNKNOWN  CallEvent_Type = 0
	CallEvent_INCOMING CallEvent_Type = 1 // caller server -> callee server: start a call
	CallEvent_RINGING  CallEvent_Type = 2 // callee server -> caller server: callee is ringing
	CallEvent_ANSWER   CallEvent_Type = 3 // callee server -> caller server: callee answered (sdp)
	CallEvent_ICE      CallEvent_Type = 4 // either direction: a trickled ICE candidate
	CallEvent_HANGUP   CallEvent_Type = 5 // either direction: call ended (reason)
	CallEvent_BUSY     CallEvent_Type = 6 // callee server -> caller server: callee unavailable
)

// Enum value maps for CallEvent_Type.
var (
	CallEvent_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "INCOMING",
		2: "RINGING",
		3: "ANSWER",
		4: "ICE",
		5: "HANGUP",
		6: "BUSY",
	}
	CallEvent_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"INCOMING": 1,
		"RINGING":  2,
		"ANSWER":   3,
		"ICE":      4,
		"HANGUP":   5,
		"BUSY":     6,
	}
)

func (x CallEvent_Type) Enum() *CallEvent_Type {
	p := new(CallEvent_Type)
	*p = x
	return p
}

func (x CallEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ocnserver_proto_enumTypes[0].Descriptor()
}

func (CallEvent_Type) Type() protoreflect.EnumType {
	return &file_ocnserver_proto_enumTypes[0]
}

func (x CallEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallEvent_Type.Descriptor instead.
func (CallEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{0, 0}
}

// Events exchanged over BridgeCall between two OCN servers.
type CallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Type          CallEvent_Type         `protobuf:"varint,2,opt,name=type,proto3,enum=ocn.ocnserver.CallEvent_Type" json:"type,omitempty"`
	CallerNumber  *common.PhoneNumber    `protobuf:"bytes,3,opt,name=caller_number,json=callerNumber,proto3" json:"caller_number,omitempty"`
	CallerName    *common.DisplayName    `protobuf:"bytes,4,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"` // 7-digit local number being called
	Sdp           *common.SDPSession     `protobuf:"bytes,6,opt,name=sdp,proto3" json:"sdp,omitempty"`                 // offer (INCOMING) / answer (ANSWER)
	Candidate     *common.ICECandidate   `protobuf:"bytes,7,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"` // HANGUP reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_ocnserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{0}
}

func (x *CallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallEvent) GetType() CallEvent_Type {
	if x != nil {
		return x.Type
	}
	return CallEvent_UNKNOWN
}

func (x *CallEvent) GetCallerNumber() *common.PhoneNumber {
	if x != nil {
		return x.CallerNumber
	}
	return nil
}

func (x *CallEvent) GetCallerName() *common.DisplayName {
	if x != nil {
		return x.CallerName
	}
	return nil
}

func (x *CallEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CallEvent) GetSdp() *common.SDPSession {
	if x != nil {
		return x.Sdp
	}
	return nil
}

func (x *CallEvent) GetCandidate() *common.ICECandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *CallEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IncomingCallRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CallId            string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CallerNumber      *common.PhoneNumber    `protobuf:"bytes,2,opt,name=caller_number,json=callerNumber,proto3" json:"caller_number,omitempty"`
	CallerName        *common.DisplayName    `protobuf:"bytes,3,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"`
	DestinationNumber *common.PhoneNumber    `protobuf:"bytes,4,opt,name=destination_number,json=destinationNumber,proto3" json:"destination_number,omitempty"`
	Offer             *common.SDPSession     `protobuf:"bytes,5,opt,name=offer,proto3" json:"offer,omitempty"`
	SourceAreaCode    string                 `protobuf:"bytes,6,opt,name=source_area_code,json=sourceAreaCode,proto3" json:"source_area_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IncomingCallRequest) Reset() {
	*x = IncomingCallRequest{}
	mi := &file_ocnserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallRequest) ProtoMessage() {}

func (x *IncomingCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallRequest.ProtoReflect.Descriptor instead.
func (*IncomingCallRequest) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{1}
}

func (x *IncomingCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IncomingCallRequest) GetCallerNumber() *common.PhoneNumber {
	if x != nil {
		return x.CallerNumber
	}
	return nil
}

func (x *IncomingCallRequest) GetCallerName() *common.DisplayName {
	if x != nil {
		return x.CallerName
	}
	return nil
}

func (x *IncomingCallRequest) GetDestinationNumber() *common.PhoneNumber {
	if x != nil {
		return x.DestinationNumber
	}
	return nil
}

func (x *IncomingCallRequest) GetOffer() *common.SDPSession {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *IncomingCallRequest) GetSourceAreaCode() string {
	if x != nil {
		return x.SourceAreaCode
	}
	return ""
}

type IncomingCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Answer        *common.SDPSession     `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallResponse) Reset() {
	*x = IncomingCallResponse{}
	mi := &file_ocnserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallResponse) ProtoMessage() {}

func (x *IncomingCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallResponse.ProtoReflect.Descriptor instead.
func (*IncomingCallResponse) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{2}
}

func (x *IncomingCallResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IncomingCallResponse) GetAnswer() *common.SDPSession {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *IncomingCallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CallAnsweredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Answer        *common.SDPSession     `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAnsweredRequest) Reset() {
	*x = CallAnsweredRequest{}
	mi := &file_ocnserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAnsweredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAnsweredRequest) ProtoMessage() {}

func (x *CallAnsweredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAnsweredRequest.ProtoReflect.Descriptor instead.
func (*CallAnsweredRequest) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{3}
}

func (x *CallAnsweredRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallAnsweredRequest) GetAnswer() *common.SDPSession {
	if x != nil {
		return x.Answer
	}
	return nil
}

type CallAnsweredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallAnsweredResponse) Reset() {
	*x = CallAnsweredResponse{}
	mi := &file_ocnserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallAnsweredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAnsweredResponse) ProtoMessage() {}

func (x *CallAnsweredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAnsweredResponse.ProtoReflect.Descriptor instead.
func (*CallAnsweredResponse) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{4}
}

func (x *CallAnsweredResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CallEndedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEndedRequest) Reset() {
	*x = CallEndedRequest{}
	mi := &file_ocnserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEndedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEndedRequest) ProtoMessage() {}

func (x *CallEndedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEndedRequest.ProtoReflect.Descriptor instead.
func (*CallEndedRequest) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{5}
}

func (x *CallEndedRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallEndedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ICEExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Candidates    []*common.ICECandidate `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICEExchangeRequest) Reset() {
	*x = ICEExchangeRequest{}
	mi := &file_ocnserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICEExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICEExchangeRequest) ProtoMessage() {}

func (x *ICEExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICEExchangeRequest.ProtoReflect.Descriptor instead.
func (*ICEExchangeRequest) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{6}
}

func (x *ICEExchangeRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ICEExchangeRequest) GetCandidates() []*common.ICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ICEExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICEExchangeResponse) Reset() {
	*x = ICEExchangeResponse{}
	mi := &file_ocnserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICEExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICEExchangeResponse) ProtoMessage() {}

func (x *ICEExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocnserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICEExchangeResponse.ProtoReflect.Descriptor instead.
func (*ICEExchangeResponse) Descriptor() ([]byte, []int) {
	return file_ocnserver_proto_rawDescGZIP(), []int{7}
}

func (x *ICEExchangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ocnserver_proto protoreflect.FileDescriptor

const file_ocnserver_proto_rawDesc = "" +
	"\n" +
	"\x0focnserver.proto\x12\rocn.ocnserver\x1a\fcommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x03\n" +
	"\tCallEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.ocn.ocnserver.CallEvent.TypeR\x04type\x12<\n" +
	"\rcaller_number\x18\x03 \x01(\v2\x17.ocn.common.PhoneNumberR\fcallerNumber\x128\n" +
	"\vcaller_name\x18\x04 \x01(\v2\x17.ocn.common.DisplayNameR\n" +
	"callerName\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12(\n" +
	"\x03sdp\x18\x06 \x01(\v2\x16.ocn.common.SDPSessionR\x03sdp\x126\n" +
	"\tcandidate\x18\a \x01(\v2\x18.ocn.common.ICECandidateR\tcandidate\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"Y\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bINCOMING\x10\x01\x12\v\n" +
	"\aRINGING\x10\x02\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x03\x12\a\n" +
	"\x03ICE\x10\x04\x12\n" +
	"\n" +
	"\x06HANGUP\x10\x05\x12\b\n" +
	"\x04BUSY\x10\x06\"\xc6\x02\n" +
	"\x13IncomingCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12<\n" +
	"\rcaller_number\x18\x02 \x01(\v2\x17.ocn.common.PhoneNumberR\fcallerNumber\x128\n" +
	"\vcaller_name\x18\x03 \x01(\v2\x17.ocn.common.DisplayNameR\n" +
	"callerName\x12F\n" +
	"\x12destination_number\x18\x04 \x01(\v2\x17.ocn.common.PhoneNumberR\x11destinationNumber\x12,\n" +
	"\x05offer\x18\x05 \x01(\v2\x16.ocn.common.SDPSessionR\x05offer\x12(\n" +
	"\x10source_area_code\x18\x06 \x01(\tR\x0esourceAreaCode\"\x87\x01\n" +
	"\x14IncomingCallResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12.\n" +
	"\x06answer\x18\x02 \x01(\v2\x16.ocn.common.SDPSessionR\x06answer\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"^\n" +
	"\x13CallAnsweredRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12.\n" +
	"\x06answer\x18\x02 \x01(\v2\x16.ocn.common.SDPSessionR\x06answer\"0\n" +
	"\x14CallAnsweredResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x10CallEndedRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"g\n" +
	"\x12ICEExchangeRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x128\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x18.ocn.common.ICECandidateR\n" +
	"candidates\"/\n" +
	"\x13ICEExchangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaf\x03\n" +
	"\x10OCNServerService\x12W\n" +
	"\fIncomingCall\x12\".ocn.ocnserver.IncomingCallRequest\x1a#.ocn.ocnserver.IncomingCallResponse\x12W\n" +
	"\fCallAnswered\x12\".ocn.ocnserver.CallAnsweredRequest\x1a#.ocn.ocnserver.CallAnsweredResponse\x12D\n" +
	"\tCallEnded\x12\x1f.ocn.ocnserver.CallEndedRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x14ICECandidateExchange\x12!.ocn.ocnserver.ICEExchangeRequest\x1a\".ocn.ocnserver.ICEExchangeResponse\x12D\n" +
	"\n" +
	"BridgeCall\x12\x18.ocn.ocnserver.CallEvent\x1a\x18.ocn.ocnserver.CallEvent(\x010\x01B5Z3github.com/open-carrier-network/ocn/proto/ocnserverb\x06proto3"

var (
	file_ocnserver_proto_rawDescOnce sync.Once
	file_ocnserver_proto_rawDescData []byte
)

func file_ocnserver_proto_rawDescGZIP() []byte {
	file_ocnserver_proto_rawDescOnce.Do(func() {
		file_ocnserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocnserver_proto_rawDesc), len(file_ocnserver_proto_rawDesc)))
	})
	return file_ocnserver_proto_rawDescData
}

var file_ocnserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ocnserver_proto_goTypes = []any{
	(CallEvent_Type)(0),          // 0: ocn.ocnserver.CallEvent.Type
	(*CallEvent)(nil),            // 1: ocn.ocnserver.CallEvent
	(*IncomingCallRequest)(nil),  // 2: ocn.ocnserver.IncomingCallRequest
	(*IncomingCallResponse)(nil), // 3: ocn.ocnserver.IncomingCallResponse
	(*CallAnsweredRequest)(nil),  // 4: ocn.ocnserver.CallAnsweredRequest
	(*CallAnsweredResponse)(nil), // 5: ocn.ocnserver.CallAnsweredResponse
	(*CallEndedRequest)(nil),     // 6: ocn.ocnserver.CallEndedRequest
	(*ICEExchangeRequest)(nil),   // 7: ocn.ocnserver.ICEExchangeRequest
	(*ICEExchangeResponse)(nil),  // 8: ocn.ocnserver.ICEExchangeResponse
	(*common.PhoneNumber)(nil),   // 9: ocn.common.PhoneNumber
	(*common.DisplayName)(nil),   // 10: ocn.common.DisplayName
	(*common.SDPSession)(nil),    // 11: ocn.common.SDPSession
	(*common.ICECandidate)(nil),  // 12: ocn.common.ICECandidate
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_ocnserver_proto_depIdxs = []int32{
	0,  // 0: ocn.ocnserver.CallEvent.type:type_name -> ocn.ocnserver.CallEvent.Type
	9,  // 1: ocn.ocnserver.CallEvent.caller_number:type_name -> ocn.common.PhoneNumber
	10, // 2: ocn.ocnserver.CallEvent.caller_name:type_name -> ocn.common.DisplayName
	11, // 3: ocn.ocnserver.CallEvent.sdp:type_name -> ocn.common.SDPSession
	12, // 4: ocn.ocnserver.CallEvent.candidate:type_name -> ocn.common.ICECandidate
	9,  // 5: ocn.ocnserver.IncomingCallRequest.caller_number:type_name -> ocn.common.PhoneNumber
	10, // 6: ocn.ocnserver.IncomingCallRequest.caller_name:type_name -> ocn.common.DisplayName
	9,  // 7: ocn.ocnserver.IncomingCallRequest.destination_number:type_name -> ocn.common.PhoneNumber
	11, // 8: ocn.ocnserver.IncomingCallRequest.offer:type_name -> ocn.common.SDPSession
	11, // 9: ocn.ocnserver.IncomingCallResponse.answer:type_name -> ocn.common.SDPSession
	11, // 10: ocn.ocnserver.CallAnsweredRequest.answer:type_name -> ocn.common.SDPSession
	12, // 11: ocn.ocnserver.ICEExchangeRequest.candidates:type_name -> ocn.common.ICECandidate
	2,  // 12: ocn.ocnserver.OCNServerService.IncomingCall:input_type -> ocn.ocnserver.IncomingCallRequest
	4,  // 13: ocn.ocnserver.OCNServerService.CallAnswered:input_type -> ocn.ocnserver.CallAnsweredRequest
	6,  // 14: ocn.ocnserver.OCNServerService.CallEnded:input_type -> ocn.ocnserver.CallEndedRequest
	7,  // 15: ocn.ocnserver.OCNServerService.ICECandidateExchange:input_type -> ocn.ocnserver.ICEExchangeRequest
	1,  // 16: ocn.ocnserver.OCNServerService.BridgeCall:input_type -> ocn.ocnserver.CallEvent
	3,  // 17: ocn.ocnserver.OCNServerService.IncomingCall:output_type -> ocn.ocnserver.IncomingCallResponse
	5,  // 18: ocn.ocnserver.OCNServerService.CallAnswered:output_type -> ocn.ocnserver.CallAnsweredResponse
	13, // 19: ocn.ocnserver.OCNServerService.CallEnded:output_type -> google.protobuf.Empty
	8,  // 20: ocn.ocnserver.OCNServerService.ICECandidateExchange:output_type -> ocn.ocnserver.ICEExchangeResponse
	1,  // 21: ocn.ocnserver.OCNServerService.BridgeCall:output_type -> ocn.ocnserver.CallEvent
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ocnserver_proto_init() }
func file_ocnserver_proto_init() {
	if File_ocnserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocnserver_proto_rawDesc), len(file_ocnserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocnserver_proto_goTypes,
		DependencyIndexes: file_ocnserver_proto_depIdxs,
		EnumInfos:         file_ocnserver_proto_enumTypes,
		MessageInfos:      file_ocnserver_proto_msgTypes,
	}.Build()
	File_ocnserver_proto = out.File
	file_ocnserver_proto_goTypes = nil
	file_ocnserver_proto_depIdxs = nil
}
