// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ocnserver.proto

package ocnserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCNServerService_IncomingCall_FullMethodName         = "/ocn.ocnserver.OCNServerService/IncomingCall"
	OCNServerService_CallAnswered_FullMethodName         = "/ocn.ocnserver.OCNServerService/CallAnswered"
	OCNServerService_CallEnded_FullMethodName            = "/ocn.ocnserver.OCNServerService/CallEnded"
	OCNServerService_ICECandidateExchange_FullMethodName = "/ocn.ocnserver.OCNServerService/ICECandidateExchange"
	OCNServerService_BridgeCall_FullMethodName           = "/ocn.ocnserver.OCNServerService/BridgeCall"
)

// OCNServerServiceClient is the client API for OCNServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OCNServer-to-OCNServer service for cross-server calls
type OCNServerServiceClient interface {
	IncomingCall(ctx context.Context, in *IncomingCallRequest, opts ...grpc.CallOption) (*IncomingCallResponse, error)
	CallAnswered(ctx context.Context, in *CallAnsweredRequest, opts ...grpc.CallOption) (*CallAnsweredResponse, error)
	CallEnded(ctx context.Context, in *CallEndedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ICECandidateExchange(ctx context.Context, in *ICEExchangeRequest, opts ...grpc.CallOption) (*ICEExchangeResponse, error)
	// Bidirectional relay for a cross-server call. The caller's server dials the
	// callee's server and both exchange CallEvents over the stream.
	BridgeCall(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CallEvent, CallEvent], error)
}

type oCNServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOCNServerServiceClient(cc grpc.ClientConnInterface) OCNServerServiceClient {
	return &oCNServerServiceClient{cc}
}

func (c *oCNServerServiceClient) IncomingCall(ctx context.Context, in *IncomingCallRequest, opts ...grpc.CallOption) (*IncomingCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomingCallResponse)
	err := c.cc.Invoke(ctx, OCNServerService_IncomingCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNServerServiceClient) CallAnswered(ctx context.Context, in *CallAnsweredRequest, opts ...grpc.CallOption) (*CallAnsweredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallAnsweredResponse)
	err := c.cc.Invoke(ctx, OCNServerService_CallAnswered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNServerServiceClient) CallEnded(ctx context.Context, in *CallEndedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OCNServerService_CallEnded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNServerServiceClient) ICECandidateExchange(ctx context.Context, in *ICEExchangeRequest, opts ...grpc.CallOption) (*ICEExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ICEExchangeResponse)
	err := c.cc.Invoke(ctx, OCNServerService_ICECandidateExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCNServerServiceClient) BridgeCall(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CallEvent, CallEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OCNServerService_ServiceDesc.Streams[0], OCNServerService_BridgeCall_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallEvent, CallEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OCNServerService_BridgeCallClient = grpc.BidiStreamingClient[CallEvent, CallEvent]

// OCNServerServiceServer is the server API for OCNServerService service.
// All implementations must embed UnimplementedOCNServerServiceServer
// for forward compatibility.
//
// OCNServer-to-OCNServer service for cross-server calls
type OCNServerServiceServer interface {
	IncomingCall(context.Context, *IncomingCallRequest) (*IncomingCallResponse, error)
	CallAnswered(context.Context, *CallAnsweredRequest) (*CallAnsweredResponse, error)
	CallEnded(context.Context, *CallEndedRequest) (*emptypb.Empty, error)
	ICECandidateExchange(context.Context, *ICEExchangeRequest) (*ICEExchangeResponse, error)
	// Bidirectional relay for a cross-server call. The caller's server dials the
	// callee's server and both exchange CallEvents over the stream.
	BridgeCall(grpc.BidiStreamingServer[CallEvent, CallEvent]) error
	mustEmbedUnimplementedOCNServerServiceServer()
}

// UnimplementedOCNServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCNServerServiceServer struct{}

func (UnimplementedOCNServerServiceServer) IncomingCall(context.Context, *IncomingCallRequest) (*IncomingCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncomingCall not implemented")
}
func (UnimplementedOCNServerServiceServer) CallAnswered(context.Context, *CallAnsweredRequest) (*CallAnsweredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallAnswered not implemented")
}
func (UnimplementedOCNServerServiceServer) CallEnded(context.Context, *CallEndedRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CallEnded not implemented")
}
func (UnimplementedOCNServerServiceServer) ICECandidateExchange(context.Context, *ICEExchangeRequest) (*ICEExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ICECandidateExchange not implemented")
}
func (UnimplementedOCNServerServiceServer) BridgeCall(grpc.BidiStreamingServer[CallEvent, CallEvent]) error {
	return status.Error(codes.Unimplemented, "method BridgeCall not implemented")
}
func (UnimplementedOCNServerServiceServer) mustEmbedUnimplementedOCNServerServiceServer() {}
func (UnimplementedOCNServerServiceServer) testEmbeddedByValue()                          {}

// UnsafeOCNServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCNServerServiceServer will
// result in compilation errors.
type UnsafeOCNServerServiceServer interface {
	mustEmbedUnimplementedOCNServerServiceServer()
}

func RegisterOCNServerServiceServer(s grpc.ServiceRegistrar, srv OCNServerServiceServer) {
	// If the following call panics, it indicates UnimplementedOCNServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCNServerService_ServiceDesc, srv)
}

func _OCNServerService_IncomingCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNServerServiceServer).IncomingCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNServerService_IncomingCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNServerServiceServer).IncomingCall(ctx, req.(*IncomingCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNServerService_CallAnswered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallAnsweredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNServerServiceServer).CallAnswered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNServerService_CallAnswered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNServerServiceServer).CallAnswered(ctx, req.(*CallAnsweredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNServerService_CallEnded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallEndedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNServerServiceServer).CallEnded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNServerService_CallEnded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNServerServiceServer).CallEnded(ctx, req.(*CallEndedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNServerService_ICECandidateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ICEExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCNServerServiceServer).ICECandidateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCNServerService_ICECandidateExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCNServerServiceServer).ICECandidateExchange(ctx, req.(*ICEExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCNServerService_BridgeCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OCNServerServiceServer).BridgeCall(&grpc.GenericServerStream[CallEvent, CallEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OCNServerService_BridgeCallServer = grpc.BidiStreamingServer[CallEvent, CallEvent]

// OCNServerService_ServiceDesc is the grpc.ServiceDesc for OCNServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCNServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocn.ocnserver.OCNServerService",
	HandlerType: (*OCNServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IncomingCall",
			Handler:    _OCNServerService_IncomingCall_Handler,
		},
		{
			MethodName: "CallAnswered",
			Handler:    _OCNServerService_CallAnswered_Handler,
		},
		{
			MethodName: "CallEnded",
			Handler:    _OCNServerService_CallEnded_Handler,
		},
		{
			MethodName: "ICECandidateExchange",
			Handler:    _OCNServerService_ICECandidateExchange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BridgeCall",
			Handler:       _OCNServerService_BridgeCall_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ocnserver.proto",
}
